/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0c0e11',
        'on-secondary-fixed': '#001f24',
        'primary': '#efffe3',
        'inverse-surface': '#e2e2e6',
        'on-tertiary-container': '#736000',
        'inverse-primary': '#106e00',
        'primary-container': '#39ff14',
        'surface-bright': '#37393d',
        'secondary-fixed-dim': '#00daf3',
        'on-surface': '#e2e2e6',
        'on-secondary-container': '#00616d',
        'surface-container': '#1e2023',
        'on-secondary-fixed-variant': '#004f58',
        'surface-container-high': '#282a2d',
        'secondary-fixed': '#9cf0ff',
        'surface-variant': '#333538',
        'primary-fixed': '#79ff5b',
        'tertiary-fixed': '#ffe16d',
        'outline-variant': '#3c4b35',
        'tertiary-fixed-dim': '#e9c400',
        'tertiary': '#fff9f0',
        'surface-tint': '#2ae500',
        'secondary-container': '#00e3fd',
        'error': '#ffb4ab',
        'on-tertiary-fixed-variant': '#544600',
        'on-error-container': '#ffdad6',
        'tertiary-container': '#ffdb40',
        'primary-fixed-dim': '#2ae500',
        'secondary': '#bdf4ff',
        'error-container': '#93000a',
        'on-secondary': '#00363d',
        'on-tertiary-fixed': '#221b00',
        'on-background': '#e2e2e6',
        'on-surface-variant': '#baccb0',
        'on-error': '#690005',
        'surface-dim': '#111316',
        'on-primary-fixed': '#022100',
        'outline': '#85967c',
        'on-tertiary': '#3a3000',
        'on-primary-container': '#107100',
        'on-primary': '#053900',
        'on-primary-fixed-variant': '#095300',
        'surface-container-highest': '#333538',
        'surface': '#111316',
        'background': '#111316',
        'surface-container-low': '#1a1c1f',
        'inverse-on-surface': '#2f3034',
      },
      spacing: {
        'base': '8px',
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '40px',
        'gutter': '24px',
        'xl': '64px',
        'margin': '32px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
