import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateB2bSchema1710000000000 implements MigrationInterface {
  name = 'CreateB2bSchema1710000000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(120) NOT NULL, slug varchar(80) NOT NULL UNIQUE, status varchar(40) NOT NULL DEFAULT 'ACTIVE', timezone varchar(64) NOT NULL DEFAULT 'America/Argentina/Buenos_Aires', currency varchar(3) NOT NULL DEFAULT 'ARS', "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP)`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_roles (id varchar(20) PRIMARY KEY, name varchar(80) NOT NULL)`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL REFERENCES b2b_organizations(id), email varchar(160) NOT NULL, "passwordHash" varchar(255) NOT NULL, "fullName" varchar(120) NOT NULL, status varchar(20) NOT NULL DEFAULT 'ACTIVE', "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("organizationId", email))`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_user_roles ("userId" uuid NOT NULL REFERENCES b2b_users(id) ON DELETE CASCADE, "organizationId" uuid NOT NULL REFERENCES b2b_organizations(id) ON DELETE CASCADE, "roleId" varchar(20) NOT NULL REFERENCES b2b_roles(id), PRIMARY KEY ("userId", "organizationId", "roleId"))`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_facilities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL REFERENCES b2b_organizations(id) ON DELETE CASCADE, name varchar(120) NOT NULL, address varchar(220), status varchar(20) NOT NULL DEFAULT 'ACTIVE', UNIQUE ("organizationId", name))`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_courts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL REFERENCES b2b_organizations(id) ON DELETE CASCADE, "facilityId" uuid NOT NULL REFERENCES b2b_facilities(id) ON DELETE CASCADE, name varchar(100) NOT NULL, "sportType" varchar(50) NOT NULL DEFAULT 'FUTBOL', capacity integer NOT NULL DEFAULT 10, status varchar(20) NOT NULL DEFAULT 'ACTIVE', "defaultPriceCentsArs" integer NOT NULL DEFAULT 0, UNIQUE ("facilityId", name))`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_shift_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "courtId" uuid NOT NULL REFERENCES b2b_courts(id) ON DELETE CASCADE, weekday smallint NOT NULL, "startTime" time NOT NULL, "endTime" time NOT NULL, "durationHours" smallint NOT NULL CHECK ("durationHours" IN (1, 2)), "priceCentsArs" integer NOT NULL, active boolean NOT NULL DEFAULT true, UNIQUE ("courtId", weekday, "startTime"))`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_shifts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL REFERENCES b2b_organizations(id) ON DELETE CASCADE, "courtId" uuid NOT NULL REFERENCES b2b_courts(id) ON DELETE CASCADE, "startsAt" timestamptz NOT NULL, "endsAt" timestamptz NOT NULL, "priceCentsArs" integer NOT NULL, status varchar(20) NOT NULL DEFAULT 'AVAILABLE', UNIQUE ("courtId", "startsAt"))`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_availability_blocks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL REFERENCES b2b_organizations(id) ON DELETE CASCADE, "courtId" uuid NOT NULL REFERENCES b2b_courts(id) ON DELETE CASCADE, "startsAt" timestamptz NOT NULL, "endsAt" timestamptz NOT NULL, reason varchar(240) NOT NULL, "createdBy" uuid NOT NULL REFERENCES b2b_users(id))`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_bookings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL REFERENCES b2b_organizations(id) ON DELETE CASCADE, "courtId" uuid NOT NULL REFERENCES b2b_courts(id), "shiftId" uuid NOT NULL REFERENCES b2b_shifts(id), "clientUserId" uuid NOT NULL REFERENCES b2b_users(id), status varchar(20) NOT NULL DEFAULT 'PENDING', "priceCentsArs" integer NOT NULL, notes varchar(500), "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP)`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS b2b_active_booking_per_shift ON b2b_bookings ("shiftId") WHERE status IN ('PENDING', 'CONFIRMED')`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_booking_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "bookingId" uuid NOT NULL REFERENCES b2b_bookings(id) ON DELETE CASCADE, "actorUserId" uuid NOT NULL REFERENCES b2b_users(id), "fromStatus" varchar(20), "toStatus" varchar(20) NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP)`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS b2b_notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL REFERENCES b2b_organizations(id) ON DELETE CASCADE, "recipientUserId" uuid NOT NULL REFERENCES b2b_users(id) ON DELETE CASCADE, type varchar(40) NOT NULL, severity varchar(12) NOT NULL, title varchar(255) NOT NULL, body varchar(500) NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', read boolean NOT NULL DEFAULT false, "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP)`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_b2b_notifications_recipient_created ON b2b_notifications ("recipientUserId", "createdAt")`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_b2b_notifications_recipient_read ON b2b_notifications ("recipientUserId", read)`);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS b2b_booking_events, b2b_bookings, b2b_availability_blocks, b2b_shifts, b2b_shift_rules, b2b_courts, b2b_facilities, b2b_user_roles, b2b_users, b2b_roles, b2b_organizations, b2b_notifications CASCADE');
  }
}